services:
  medicine-bot:
    image: greem4/medicine-bot:latest
    restart: always
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      TOKEN_BOT: ${TOKEN_BOT}
      API_URL: ${API_URL}
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
