app:
  bot:
    admin-id: ${ADMIN_ID}
    botToken: ${TOKEN_BOT}
    botUsername: ${BOT_USERNAME}
medicine:
  api:
    url: ${API_URL}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  output:
    ansi:
      enabled: always

logging:
  config: classpath:logback-spring.xml