app:
  bot:
    botToken: ${TOKEN_BOT}
    botUsername: ${BOT_USERNAME}
medicine:
  api:
    url: ${API_URL}

spring:
  output:
    ansi:
      enabled: always

logging:
  config: classpath:logback-spring.xml